services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'CHANGE_THIS_PASSWORD'
      FTLCONF_LOCAL_IPV4: '192.168.4.1'
    volumes:
      - '/mnt/storage/pihole/etc/:/etc/pihole'
      - '/mnt/storage/pihole/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
